export type League =
  | 'Premier League'
  | 'LaLiga'
  | 'Bundesliga'
  | 'Serie A'
  | 'Ligue 1';

export interface Team {
  name?: string;
  logo?: string;
  league?: League;
  country?: string;
  flag?: string;
  stars?: number;
  attack?: number;
  midfield?: number;
  defense?: number;
}

export interface LeagueTeams {
  name: League;
  country: string;
  teams: Team[];
}

export const leaguesData: LeagueTeams[] = [
  {
    name: 'Premier League',
    country: 'England',
    teams: [
      {
        name: 'Manchester City',
        logo: 'https://cdn.sofifa.net/meta/team/9/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 5,
        attack: 87,
        midfield: 86,
        defense: 83,
      },
      {
        name: 'Liverpool',
        logo: 'https://cdn.sofifa.net/meta/team/6/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 5,
        attack: 84,
        midfield: 82,
        defense: 84,
      },
      {
        name: 'Arsenal',
        logo: 'https://cdn.sofifa.net/meta/team/1/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 5,
        attack: 82,
        midfield: 84,
        defense: 81,
      },
      {
        name: 'Manchester United',
        logo: 'https://cdn.sofifa.net/meta/team/11/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 4.5,
        attack: 82,
        midfield: 83,
        defense: 80,
      },
      {
        name: 'Chelsea',
        logo: 'https://cdn.sofifa.net/meta/team/5/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 4.5,
        attack: 80,
        midfield: 81,
        defense: 82,
      },
      {
        name: 'Tottenham Hotspur',
        logo: 'https://cdn.sofifa.net/meta/team/18/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 4.5,
        attack: 83,
        midfield: 82,
        defense: 79,
      },
      {
        name: 'Leicester City',
        logo: 'https://cdn.sofifa.net/meta/team/95/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 4,
        attack: 79,
        midfield: 77,
        defense: 76,
      },
      {
        name: 'West Ham United',
        logo: 'https://cdn.sofifa.net/meta/team/19/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 4,
        attack: 78,
        midfield: 76,
        defense: 75,
      },
      {
        name: 'Everton',
        logo: 'https://cdn.sofifa.net/meta/team/7/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 4,
        attack: 76,
        midfield: 75,
        defense: 74,
      },
      {
        name: 'Wolverhampton Wanderers',
        logo: 'https://cdn.sofifa.net/meta/team/110/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 4,
        attack: 75,
        midfield: 74,
        defense: 73,
      },
      {
        name: 'Newcastle United',
        logo: 'https://cdn.sofifa.net/meta/team/13/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 3.5,
        attack: 74,
        midfield: 72,
        defense: 70,
      },
      {
        name: 'Southampton',
        logo: 'https://cdn.sofifa.net/meta/team/17/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 3.5,
        attack: 72,
        midfield: 70,
        defense: 69,
      },
    ],
  },
  {
    name: 'LaLiga',
    country: 'Spain',
    teams: [
      {
        name: 'Real Madrid',
        logo: 'https://cdn.sofifa.net/meta/team/243/60.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 5,
        attack: 85,
        midfield: 85,
        defense: 83,
      },
      {
        name: 'FC Barcelona',
        logo: 'https://cdn.sofifa.net/meta/team/241/60.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 5,
        attack: 84,
        midfield: 84,
        defense: 83,
      },
      {
        name: 'Atlético Madrid',
        logo: 'https://cdn.sofifa.net/meta/team/240/60.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 5,
        attack: 83,
        midfield: 82,
        defense: 85,
      },
      {
        name: 'Sevilla FC',
        logo: 'https://cdn.sofifa.net/meta/team/481/60.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 4,
        attack: 81,
        midfield: 83,
        defense: 82,
      },
      {
        name: 'Valencia CF',
        logo: 'https://cdn.sofifa.net/meta/team/461/60.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 4,
        attack: 79,
        midfield: 80,
        defense: 79,
      },
      {
        name: 'Real Betis',
        logo: 'https://cdn.sofifa.net/meta/team/449/60.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 4,
        attack: 78,
        midfield: 79,
        defense: 78,
      },
      {
        name: 'Villarreal CF',
        logo: 'https://cdn.sofifa.net/meta/team/483/60.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 4,
        attack: 77,
        midfield: 78,
        defense: 77,
      },
      {
        name: 'Athletic Bilbao',
        logo: 'https://cdn.sofifa.net/meta/team/448/60.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 4,
        attack: 76,
        midfield: 77,
        defense: 76,
      },
    ],
  },
  {
    name: 'Bundesliga',
    country: 'Germany',
    teams: [
      {
        name: 'FC Bayern München',
        logo: 'https://cdn.sofifa.net/meta/team/21/60.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 5,
        attack: 86,
        midfield: 85,
        defense: 83,
      },
      {
        name: 'Borussia Dortmund',
        logo: 'https://cdn.sofifa.net/meta/team/22/22.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 4.5,
        attack: 84,
        midfield: 82,
        defense: 79,
      },
      {
        name: 'RB Leipzig',
        logo: 'https://cdn.sofifa.net/meta/team/10/112172.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 4,
        attack: 81,
        midfield: 79,
        defense: 80,
      },
      {
        name: 'Bayer Leverkusen',
        logo: 'https://cdn.sofifa.net/meta/team/32/32.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 4,
        attack: 83,
        midfield: 81,
        defense: 77,
      },
      {
        name: 'Eintracht Frankfurt',
        logo: 'https://cdn.sofifa.net/meta/team/19/1824.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 4,
        attack: 79,
        midfield: 77,
        defense: 76,
      },
      {
        name: 'VfL Wolfsburg',
        logo: 'https://cdn.sofifa.net/meta/team/175/175.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 3.5,
        attack: 77,
        midfield: 76,
        defense: 75,
      },
      {
        name: 'FC Schalke 04',
        logo: 'https://cdn.sofifa.net/meta/team/34/34.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 3,
        attack: 75,
        midfield: 73,
        defense: 74,
      },
    ],
  },
  {
    name: 'Serie A',
    country: 'Italy',
    teams: [
      {
        name: 'Inter',
        logo: 'https://cdn.sofifa.net/meta/team/44/60.png',
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 5,
        attack: 85,
        midfield: 84,
        defense: 83,
      },
      {
        name: 'Juventus',
        logo: 'https://cdn.sofifa.net/meta/team/45/60.png',
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 4.5,
        attack: 84,
        midfield: 83,
        defense: 83,
      },
      {
        name: 'AC Milan',
        logo: 'https://cdn.sofifa.net/meta/team/47/60.png',
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 4.5,
        attack: 83,
        midfield: 82,
        defense: 82,
      },
      {
        name: 'Napoli',
        logo: 'https://cdn.sofifa.net/meta/team/48/60.png',
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 4,
        attack: 81,
        midfield: 80,
        defense: 79,
      },
      {
        name: 'Roma',
        logo: 'https://cdn.sofifa.net/meta/team/52/60.png',
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 4,
        attack: 80,
        midfield: 79,
        defense: 78,
      },
      {
        name: 'Lazio',
        logo: 'https://cdn.sofifa.net/meta/team/46/60.png',
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 4,
        attack: 82,
        midfield: 81,
        defense: 79,
      },
      {
        name: 'Fiorentina',
        logo: 'https://cdn.sofifa.net/meta/team/110374/60.png',
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 3.5,
        attack: 79,
        midfield: 77,
        defense: 76,
      },
      {
        name: 'Atalanta',
        logo: 'https://cdn.sofifa.net/meta/team/39/60.png',
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 4,
        attack: 81,
        midfield: 80,
        defense: 78,
      },
    ],
  },
];
