export type League =
  | 'Premier League'
  | 'LaLiga'
  | 'Bundesliga'
  | 'Serie A'
  | 'Saudi Pro League'
  | 'Ligue 1';

export interface Team {
  name?: string;
  logo?: string;
  league?: League;
  country?: string;
  flag?: string;
  stars?: number;
  attack?: number;
  midfield?: number;
  defense?: number;
}

export interface LeagueTeams {
  name: League;
  country: string;
  teams: Team[];
}

export const leaguesData: LeagueTeams[] = [
  {
    name: 'Premier League',
    country: 'England',
    teams: [
      {
        name: 'Manchester City',
        logo: 'https://cdn.sofifa.net/meta/team/9/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 5,
        attack: 87,
        midfield: 86,
        defense: 83,
      },
      {
        name: 'Liverpool',
        logo: 'https://cdn.sofifa.net/meta/team/6/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 5,
        attack: 84,
        midfield: 82,
        defense: 84,
      },
      {
        name: 'Arsenal',
        logo: 'https://cdn.sofifa.net/meta/team/1/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 5,
        attack: 82,
        midfield: 84,
        defense: 81,
      },
      {
        name: 'Manchester United',
        logo: 'https://cdn.sofifa.net/meta/team/11/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 4.5,
        attack: 82,
        midfield: 83,
        defense: 80,
      },
      {
        name: 'Chelsea',
        logo: 'https://cdn.sofifa.net/meta/team/5/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 4.5,
        attack: 80,
        midfield: 81,
        defense: 82,
      },
      {
        name: 'Tottenham Hotspur',
        logo: 'https://cdn.sofifa.net/meta/team/18/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 4.5,
        attack: 83,
        midfield: 82,
        defense: 79,
      },
      {
        name: 'Leicester City',
        logo: 'https://cdn.sofifa.net/meta/team/95/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 4,
        attack: 79,
        midfield: 77,
        defense: 76,
      },
      {
        name: 'West Ham United',
        logo: 'https://cdn.sofifa.net/meta/team/19/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 4,
        attack: 78,
        midfield: 76,
        defense: 75,
      },
      {
        name: 'Everton',
        logo: 'https://cdn.sofifa.net/meta/team/7/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 4,
        attack: 76,
        midfield: 75,
        defense: 74,
      },
      {
        name: 'Wolverhampton Wanderers',
        logo: 'https://cdn.sofifa.net/meta/team/110/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 4,
        attack: 75,
        midfield: 74,
        defense: 73,
      },
      {
        name: 'Newcastle United',
        logo: 'https://cdn.sofifa.net/meta/team/13/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 3.5,
        attack: 74,
        midfield: 72,
        defense: 70,
      },
      {
        name: 'Southampton',
        logo: 'https://cdn.sofifa.net/meta/team/17/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 3.5,
        attack: 72,
        midfield: 70,
        defense: 69,
      },
      {
        name: 'Aston Villa',
        logo: 'https://cdn.sofifa.net/meta/team/2/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 3.5,
        attack: 75,
        midfield: 73,
        defense: 71,
      },
      {
        name: 'Brighton & Hove Albion',
        logo: 'https://cdn.sofifa.net/meta/team/180/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 3.5,
        attack: 73,
        midfield: 74,
        defense: 72,
      },
      {
        name: 'Crystal Palace',
        logo: 'https://cdn.sofifa.net/meta/team/1791/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 3.5,
        attack: 73,
        midfield: 72,
        defense: 71,
      },
      {
        name: 'Fulham',
        logo: 'https://cdn.sofifa.net/meta/team/144/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 3,
        attack: 71,
        midfield: 69,
        defense: 68,
      },
      {
        name: 'Brentford',
        logo: 'https://cdn.sofifa.net/meta/team/1923/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 3,
        attack: 70,
        midfield: 68,
        defense: 67,
      },
      {
        name: 'Bournemouth',
        logo: 'https://cdn.sofifa.net/meta/team/91/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 3,
        attack: 68,
        midfield: 67,
        defense: 66,
      },
      {
        name: 'Nottingham Forest',
        logo: 'https://cdn.sofifa.net/meta/team/14/60.png',
        league: 'Premier League',
        country: 'England',
        flag: 'https://cdn.sofifa.net/flags/gb-eng.png',
        stars: 3,
        attack: 69,
        midfield: 68,
        defense: 67,
      },
    ],
  },
  {
    name: 'LaLiga',
    country: 'Spain',
    teams: [
      {
        name: 'Real Madrid',
        logo: 'https://cdn.sofifa.net/meta/team/243/60.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 5,
        attack: 85,
        midfield: 85,
        defense: 83,
      },
      {
        name: 'FC Barcelona',
        logo: 'https://cdn.sofifa.net/meta/team/241/60.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 5,
        attack: 84,
        midfield: 84,
        defense: 83,
      },
      {
        name: 'Atlético Madrid',
        logo: 'https://cdn.sofifa.net/meta/team/240/60.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 5,
        attack: 83,
        midfield: 82,
        defense: 85,
      },
      {
        name: 'Sevilla FC',
        logo: 'https://cdn.sofifa.net/meta/team/481/60.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 4,
        attack: 81,
        midfield: 83,
        defense: 82,
      },
      {
        name: 'Valencia CF',
        logo: 'https://cdn.sofifa.net/meta/team/461/60.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 4,
        attack: 79,
        midfield: 80,
        defense: 79,
      },
      {
        name: 'Real Betis',
        logo: 'https://cdn.sofifa.net/meta/team/449/60.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 4,
        attack: 78,
        midfield: 79,
        defense: 78,
      },
      {
        name: 'Villarreal CF',
        logo: 'https://cdn.sofifa.net/meta/team/483/60.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 4,
        attack: 77,
        midfield: 78,
        defense: 77,
      },
      {
        name: 'Athletic Bilbao',
        logo: 'https://cdn.sofifa.net/meta/team/448/60.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 4,
        attack: 76,
        midfield: 77,
        defense: 76,
      },
      {
        name: 'Alavés',
        logo: 'https://example.com/logo/alaves.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 3,
        attack: 70,
        midfield: 71,
        defense: 70,
      },
      {
        name: 'Celta Vigo',
        logo: 'https://example.com/logo/celta_vigo.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 3,
        attack: 72,
        midfield: 71,
        defense: 71,
      },
      {
        name: 'Espanyol',
        logo: 'https://example.com/logo/espanyol.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 3,
        attack: 73,
        midfield: 72,
        defense: 72,
      },
      {
        name: 'Getafe',
        logo: 'https://example.com/logo/getafe.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 3,
        attack: 71,
        midfield: 72,
        defense: 71,
      },
      {
        name: 'Granada',
        logo: 'https://example.com/logo/granada.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 3,
        attack: 70,
        midfield: 70,
        defense: 70,
      },
      {
        name: 'Levante',
        logo: 'https://example.com/logo/levante.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 3,
        attack: 69,
        midfield: 69,
        defense: 69,
      },
      {
        name: 'Osasuna',
        logo: 'https://example.com/logo/osasuna.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 3,
        attack: 70,
        midfield: 70,
        defense: 70,
      },
      {
        name: 'Rayo Vallecano',
        logo: 'https://example.com/logo/rayo_vallecano.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 3,
        attack: 70,
        midfield: 71,
        defense: 70,
      },
      {
        name: 'Mallorca',
        logo: 'https://example.com/logo/mallorca.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 3,
        attack: 70,
        midfield: 71,
        defense: 70,
      },
      {
        name: 'Cádiz',
        logo: 'https://example.com/logo/cadiz.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 3,
        attack: 70,
        midfield: 70,
        defense: 70,
      },
      {
        name: 'Elche',
        logo: 'https://example.com/logo/elche.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 3,
        attack: 69,
        midfield: 69,
        defense: 69,
      },
      {
        name: 'Almería',
        logo: 'https://example.com/logo/almeria.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 3,
        attack: 70,
        midfield: 70,
        defense: 70,
      },
      {
        name: 'Girona',
        logo: 'https://example.com/logo/girona.png',
        league: 'LaLiga',
        country: 'Spain',
        flag: 'https://cdn.sofifa.net/flags/es.png',
        stars: 3,
        attack: 71,
        midfield: 71,
        defense: 71,
      },
    ],
  },
  {
    name: 'Bundesliga',
    country: 'Germany',
    teams: [
      {
        name: 'FC Bayern München',
        logo: 'https://cdn.sofifa.net/meta/team/21/60.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 5,
        attack: 86,
        midfield: 85,
        defense: 83,
      },
      {
        name: 'Borussia Dortmund',
        logo: 'https://cdn.sofifa.net/meta/team/22/22.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 4.5,
        attack: 84,
        midfield: 82,
        defense: 79,
      },
      {
        name: 'RB Leipzig',
        logo: 'https://cdn.sofifa.net/meta/team/10/112172.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 4,
        attack: 81,
        midfield: 79,
        defense: 80,
      },
      {
        name: 'Bayer Leverkusen',
        logo: 'https://cdn.sofifa.net/meta/team/32/32.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 4,
        attack: 83,
        midfield: 81,
        defense: 77,
      },
      {
        name: 'Eintracht Frankfurt',
        logo: 'https://cdn.sofifa.net/meta/team/19/1824.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 4,
        attack: 79,
        midfield: 77,
        defense: 76,
      },
      {
        name: 'VfL Wolfsburg',
        logo: 'https://cdn.sofifa.net/meta/team/175/175.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 3.5,
        attack: 77,
        midfield: 76,
        defense: 75,
      },
      {
        name: 'FC Schalke 04',
        logo: 'https://cdn.sofifa.net/meta/team/34/34.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 3,
        attack: 75,
        midfield: 73,
        defense: 74,
      },
      {
        name: '1. FC Union Berlin',
        logo: 'https://cdn.sofifa.net/meta/team/1824/1824.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 3.5,
        attack: 75,
        midfield: 74,
        defense: 73,
      },
      {
        name: '1. FSV Mainz 05',
        logo: 'https://cdn.sofifa.net/meta/team/169/169.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 3.5,
        attack: 75,
        midfield: 74,
        defense: 73,
      },
      {
        name: 'Hertha BSC',
        logo: 'https://cdn.sofifa.net/meta/team/162/159.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 3.5,
        attack: 77,
        midfield: 75,
        defense: 74,
      },
      {
        name: 'FC Augsburg',
        logo: 'https://cdn.sofifa.net/meta/team/34/134.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 3,
        attack: 73,
        midfield: 72,
        defense: 71,
      },
      {
        name: 'TSG 1899 Hoffenheim',
        logo: 'https://cdn.sofifa.net/meta/team/24/27.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 3.5,
        attack: 76,
        midfield: 75,
        defense: 74,
      },
      {
        name: 'SC Freiburg',
        logo: 'https://cdn.sofifa.net/meta/team/25/25.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 3.5,
        attack: 75,
        midfield: 74,
        defense: 73,
      },
      {
        name: 'Borussia Mönchengladbach',
        logo: 'https://cdn.sofifa.net/meta/team/24/24.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 4,
        attack: 81,
        midfield: 79,
        defense: 78,
      },
      {
        name: 'Werder Bremen',
        logo: 'https://cdn.sofifa.net/meta/team/23/25.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 3,
        attack: 73,
        midfield: 72,
        defense: 71,
      },
      {
        name: 'VfB Stuttgart',
        logo: 'https://cdn.sofifa.net/meta/team/26/26.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 3.5,
        attack: 76,
        midfield: 75,
        defense: 74,
      },
      {
        name: 'VfL Bochum',
        logo: 'https://cdn.sofifa.net/meta/team/172/172.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 3,
        attack: 72,
        midfield: 71,
        defense: 70,
      },
      {
        name: '1. FC Heidenheim',
        logo: 'https://cdn.sofifa.net/meta/team/1122/1122.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 2.5,
        attack: 70,
        midfield: 68,
        defense: 67,
      },
      {
        name: 'Holstein Kiel',
        logo: 'https://cdn.sofifa.net/meta/team/112/112.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 3,
        attack: 72,
        midfield: 71,
        defense: 70,
      },
      {
        name: 'FC St. Pauli',
        logo: 'https://cdn.sofifa.net/meta/team/28/28.png',
        league: 'Bundesliga',
        country: 'Germany',
        flag: 'https://cdn.sofifa.net/flags/de.png',
        stars: 2.5,
        attack: 70,
        midfield: 68,
        defense: 67,
      },
    ],
  },
  {
    name: 'Serie A',
    country: 'Italy',
    teams: [
      {
        name: 'Inter',
        logo: 'https://cdn.sofifa.net/meta/team/44/60.png',
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 5,
        attack: 85,
        midfield: 84,
        defense: 83,
      },
      {
        name: 'Juventus',
        logo: 'https://cdn.sofifa.net/meta/team/45/60.png',
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 4.5,
        attack: 84,
        midfield: 83,
        defense: 83,
      },
      {
        name: 'AC Milan',
        logo: 'https://cdn.sofifa.net/meta/team/47/60.png',
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 4.5,
        attack: 83,
        midfield: 82,
        defense: 82,
      },
      {
        name: 'Napoli',
        logo: 'https://cdn.sofifa.net/meta/team/48/60.png',
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 4,
        attack: 81,
        midfield: 80,
        defense: 79,
      },
      {
        name: 'Roma',
        logo: 'https://cdn.sofifa.net/meta/team/52/60.png',
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 4,
        attack: 80,
        midfield: 79,
        defense: 78,
      },
      {
        name: 'Lazio',
        logo: 'https://cdn.sofifa.net/meta/team/46/60.png',
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 4,
        attack: 82,
        midfield: 81,
        defense: 79,
      },
      {
        name: 'Fiorentina',
        logo: 'https://cdn.sofifa.net/meta/team/110374/60.png',
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 3.5,
        attack: 79,
        midfield: 77,
        defense: 76,
      },
      {
        name: 'Atalanta',
        logo: 'https://cdn.sofifa.net/meta/team/39/60.png',
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 4,
        attack: 81,
        midfield: 80,
        defense: 78,
      },
      {
        name: 'Bologna',
        logo: 'https://cdn.sofifa.net/meta/team/46/60.png', // Please replace with the correct URL
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 3,
        attack: 77,
        midfield: 76,
        defense: 75,
      },
      {
        name: 'Venezia',
        logo: 'https://cdn.sofifa.net/meta/team/47/60.png', // Please replace with the correct URL
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 2.5,
        attack: 75,
        midfield: 74,
        defense: 73,
      },
      {
        name: 'Verona',
        logo: 'https://cdn.sofifa.net/meta/team/48/60.png', // Please replace with the correct URL
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 3,
        attack: 76,
        midfield: 75,
        defense: 74,
      },
      {
        name: 'Genoa',
        logo: 'https://cdn.sofifa.net/meta/team/52/60.png', // Please replace with the correct URL
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 3,
        attack: 76,
        midfield: 75,
        defense: 74,
      },
      {
        name: 'Cagliari',
        logo: 'https://cdn.sofifa.net/meta/team/46/60.png', // Please replace with the correct URL
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 3,
        attack: 76,
        midfield: 75,
        defense: 74,
      },
      {
        name: 'Como',
        logo: 'https://cdn.sofifa.net/meta/team/47/60.png', // Please replace with the correct URL
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 2.5,
        attack: 75,
        midfield: 74,
        defense: 73,
      },
      {
        name: 'Lecce',
        logo: 'https://cdn.sofifa.net/meta/team/48/60.png', // Please replace with the correct URL
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 2.5,
        attack: 75,
        midfield: 74,
        defense: 73,
      },
      {
        name: 'Monza',
        logo: 'https://cdn.sofifa.net/meta/team/52/60.png', // Please replace with the correct URL
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 3,
        attack: 76,
        midfield: 75,
        defense: 74,
      },
      {
        name: 'Parma',
        logo: 'https://cdn.sofifa.net/meta/team/46/60.png', // Please replace with the correct URL
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 2.5,
        attack: 75,
        midfield: 74,
        defense: 73,
      },
      {
        name: 'Torino',
        logo: 'https://cdn.sofifa.net/meta/team/47/60.png', // Please replace with the correct URL
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 3.5,
        attack: 78,
        midfield: 77,
        defense: 76,
      },
      {
        name: 'Udinese',
        logo: 'https://cdn.sofifa.net/meta/team/48/60.png', // Please replace with the correct URL
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 3,
        attack: 76,
        midfield: 75,
        defense: 74,
      },
      {
        name: 'Empoli',
        logo: 'https://cdn.sofifa.net/meta/team/52/60.png', // Please replace with the correct URL
        league: 'Serie A',
        country: 'Italy',
        flag: 'https://cdn.sofifa.net/flags/it.png',
        stars: 2.5,
        attack: 75,
        midfield: 74,
        defense: 73,
      },
    ],
  },
  {
    name: 'Ligue 1',
    country: 'France',
    teams: [
      {
        name: 'Paris Saint-Germain',
        logo: 'https://cdn.sofifa.net/meta/team/73/60.png',
        league: 'Ligue 1',
        country: 'France',
        flag: 'https://cdn.sofifa.net/flags/fr.png',
        stars: 5,
        attack: 89,
        midfield: 85,
        defense: 85,
      },
      {
        name: 'Olympique Lyonnais',
        logo: 'https://cdn.sofifa.net/meta/team/66/60.png',
        league: 'Ligue 1',
        country: 'France',
        flag: 'https://cdn.sofifa.net/flags/fr.png',
        stars: 4.5,
        attack: 80,
        midfield: 81,
        defense: 79,
      },
      {
        name: 'Olympique de Marseille',
        logo: 'https://cdn.sofifa.net/meta/team/219/60.png',
        league: 'Ligue 1',
        country: 'France',
        flag: 'https://cdn.sofifa.net/flags/fr.png',
        stars: 4,
        attack: 78,
        midfield: 79,
        defense: 77,
      },
      {
        name: 'AS Monaco',
        logo: 'https://cdn.sofifa.net/meta/team/69/60.png',
        league: 'Ligue 1',
        country: 'France',
        flag: 'https://cdn.sofifa.net/flags/fr.png',
        stars: 4,
        attack: 77,
        midfield: 78,
        defense: 76,
      },
      {
        name: 'Lille OSC',
        logo: 'https://cdn.sofifa.net/meta/team/65/60.png',
        league: 'Ligue 1',
        country: 'France',
        flag: 'https://cdn.sofifa.net/flags/fr.png',
        stars: 4,
        attack: 76,
        midfield: 77,
        defense: 75,
      },
      {
        name: 'Stade Rennais FC',
        logo: 'https://cdn.sofifa.net/meta/team/74/60.png',
        league: 'Ligue 1',
        country: 'France',
        flag: 'https://cdn.sofifa.net/flags/fr.png',
        stars: 3.5,
        attack: 75,
        midfield: 76,
        defense: 74,
      },
      {
        name: 'Angers SCO',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Angers_SCO_logo.svg/1200px-Angers_SCO_logo.svg.png',
        league: 'Ligue 1',
        country: 'France',
        flag: 'https://cdn.sofifa.net/flags/fr.png',
        stars: 3,
        attack: 69,
        midfield: 70,
        defense: 68,
      },
      {
        name: 'Stade Brestois 29',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/81/Stade_Brestois_29_logo.svg/1200px-Stade_Brestois_29_logo.svg.png',
        league: 'Ligue 1',
        country: 'France',
        flag: 'https://cdn.sofifa.net/flags/fr.png',
        stars: 3,
        attack: 68,
        midfield: 69,
        defense: 67,
      },
      {
        name: 'Le Havre AC',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/66/Le_Havre_AC_crest.svg/1200px-Le_Havre_AC_crest.svg.png',
        league: 'Ligue 1',
        country: 'France',
        flag: 'https://cdn.sofifa.net/flags/fr.png',
        stars: 3,
        attack: 67,
        midfield: 68,
        defense: 66,
      },
      {
        name: 'RC Lens',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f5/RC_Lens_logo.svg/1200px-RC_Lens_logo.svg.png',
        league: 'Ligue 1',
        country: 'France',
        flag: 'https://cdn.sofifa.net/flags/fr.png',
        stars: 4,
        attack: 75,
        midfield: 76,
        defense: 74,
      },
      {
        name: 'Montpellier HSC',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Montpellier_HSC_logo.svg/1200px-Montpellier_HSC_logo.svg.png',
        league: 'Ligue 1',
        country: 'France',
        flag: 'https://cdn.sofifa.net/flags/fr.png',
        stars: 3.5,
        attack: 72,
        midfield: 73,
        defense: 71,
      },
      {
        name: 'FC Nantes',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3a/FC_Nantes_logo.svg/1200px-FC_Nantes_logo.svg.png',
        league: 'Ligue 1',
        country: 'France',
        flag: 'https://cdn.sofifa.net/flags/fr.png',
        stars: 3.5,
        attack: 71,
        midfield: 72,
        defense: 70,
      },
      {
        name: 'OGC Nice',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e8/OGC_Nice_logo.svg/1200px-OGC_Nice_logo.svg.png',
        league: 'Ligue 1',
        country: 'France',
        flag: 'https://cdn.sofifa.net/flags/fr.png',
        stars: 3.5,
        attack: 74,
        midfield: 75,
        defense: 73,
      },
      {
        name: 'AJ Auxerre',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e0/AJ_Auxerre_logo.svg/1200px-AJ_Auxerre_logo.svg.png',
        league: 'Ligue 1',
        country: 'France',
        flag: 'https://cdn.sofifa.net/flags/fr.png',
        stars: 3,
        attack: 67,
        midfield: 68,
        defense: 66,
      },
      {
        name: 'Stade de Reims',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/15/Stade_de_Reims_logo.svg/1200px-Stade_de_Reims_logo.svg.png',
        league: 'Ligue 1',
        country: 'France',
        flag: 'https://cdn.sofifa.net/flags/fr.png',
        stars: 3.5,
        attack: 70,
        midfield: 71,
        defense: 69,
      },
      {
        name: 'AS Saint-Étienne',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cf/AS_Saint-%C3%89tienne_logo.svg/1200px-AS_Saint-%C3%89tienne_logo.svg.png',
        league: 'Ligue 1',
        country: 'France',
        flag: 'https://cdn.sofifa.net/flags/fr.png',
        stars: 3,
        attack: 68,
        midfield: 69,
        defense: 67,
      },
      {
        name: 'RC Strasbourg Alsace',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d1/RC_Strasbourg_logo.svg/1200px-RC_Strasbourg_logo.svg.png',
        league: 'Ligue 1',
        country: 'France',
        flag: 'https://cdn.sofifa.net/flags/fr.png',
        stars: 3.5,
        attack: 71,
        midfield: 72,
        defense: 70,
      },
      {
        name: 'Toulouse FC',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/76/Toulouse_FC_logo.svg/1200px-Toulouse_FC_logo.svg.png',
        league: 'Ligue 1',
        country: 'France',
        flag: 'https://cdn.sofifa.net/flags/fr.png',
        stars: 3,
        attack: 67,
        midfield: 68,
        defense: 66,
      },
    ],
  },
  {
    name: 'Saudi Pro League',
    country: 'Saudi Arabia',
    teams: [
      {
        name: 'Al-Hilal',
        logo: 'https://example.com/saudi/alhilal.png',
        league: 'Saudi Pro League',
        country: 'Saudi Arabia',
        flag: 'https://example.com/flags/saudiarabia.png',
        stars: 5,
        attack: 80,
        midfield: 78,
        defense: 77,
      },
      {
        name: 'Al-Nassr',
        logo: 'https://example.com/saudi/alnassr.png',
        league: 'Saudi Pro League',
        country: 'Saudi Arabia',
        flag: 'https://example.com/flags/saudiarabia.png',
        stars: 4.5,
        attack: 78,
        midfield: 76,
        defense: 75,
      },
      {
        name: 'Al-Ittihad',
        logo: 'https://example.com/saudi/alittihad.png',
        league: 'Saudi Pro League',
        country: 'Saudi Arabia',
        flag: 'https://example.com/flags/saudiarabia.png',
        stars: 4.5,
        attack: 77,
        midfield: 75,
        defense: 74,
      },
      {
        name: 'Al-Ahli',
        logo: 'https://example.com/saudi/alahli.png',
        league: 'Saudi Pro League',
        country: 'Saudi Arabia',
        flag: 'https://example.com/flags/saudiarabia.png',
        stars: 4,
        attack: 76,
        midfield: 74,
        defense: 73,
      },
      {
        name: 'Al-Faisaly',
        logo: 'https://example.com/saudi/alfaisaly.png',
        league: 'Saudi Pro League',
        country: 'Saudi Arabia',
        flag: 'https://example.com/flags/saudiarabia.png',
        stars: 3.5,
        attack: 73,
        midfield: 70,
        defense: 70,
      },
      {
        name: 'Al-Taawoun',
        logo: 'https://example.com/saudi/altaawoun.png',
        league: 'Saudi Pro League',
        country: 'Saudi Arabia',
        flag: 'https://example.com/flags/saudiarabia.png',
        stars: 3.5,
        attack: 72,
        midfield: 71,
        defense: 69,
      },
      {
        name: 'Al-Ahli Jeddah',
        logo: 'https://example.com/saudi/alahlijeddah.png',
        league: 'Saudi Pro League',
        country: 'Saudi Arabia',
        flag: 'https://example.com/flags/saudiarabia.png',
        stars: 4,
        attack: 76,
        midfield: 74,
        defense: 73,
      },
      {
        name: 'Al-Wehda Mecca',
        logo: 'https://example.com/saudi/alwehdamecca.png',
        league: 'Saudi Pro League',
        country: 'Saudi Arabia',
        flag: 'https://example.com/flags/saudiarabia.png',
        stars: 3.5,
        attack: 72,
        midfield: 70,
        defense: 71,
      },
      {
        name: 'Al-Ettifaq',
        logo: 'https://example.com/saudi/alettifaq.png',
        league: 'Saudi Pro League',
        country: 'Saudi Arabia',
        flag: 'https://example.com/flags/saudiarabia.png',
        stars: 3,
        attack: 70,
        midfield: 68,
        defense: 69,
      },
      {
        name: 'Al-Ittihad Jeddah',
        logo: 'https://example.com/saudi/alittihadjeddah.png',
        league: 'Saudi Pro League',
        country: 'Saudi Arabia',
        flag: 'https://example.com/flags/saudiarabia.png',
        stars: 4.5,
        attack: 77,
        midfield: 75,
        defense: 74,
      },
      {
        name: 'Al-Qadisiyah',
        logo: 'https://example.com/saudi/alqadisiyah.png',
        league: 'Saudi Pro League',
        country: 'Saudi Arabia',
        flag: 'https://example.com/flags/saudiarabia.png',
        stars: 3,
        attack: 69,
        midfield: 67,
        defense: 68,
      },
      {
        name: 'Al-Nassr Riyadh',
        logo: 'https://example.com/saudi/alnassriyadh.png',
        league: 'Saudi Pro League',
        country: 'Saudi Arabia',
        flag: 'https://example.com/flags/saudiarabia.png',
        stars: 4.5,
        attack: 78,
        midfield: 76,
        defense: 75,
      },
      {
        name: 'Al-Orobah',
        logo: 'https://example.com/saudi/alorobah.png',
        league: 'Saudi Pro League',
        country: 'Saudi Arabia',
        flag: 'https://example.com/flags/saudiarabia.png',
        stars: 2.5,
        attack: 68,
        midfield: 66,
        defense: 66,
      },
      {
        name: 'Al-Ohod',
        logo: 'https://example.com/saudi/alohod.png',
        league: 'Saudi Pro League',
        country: 'Saudi Arabia',
        flag: 'https://example.com/flags/saudiarabia.png',
        stars: 2.5,
        attack: 68,
        midfield: 65,
        defense: 66,
      },
      {
        name: 'Al-Raed',
        logo: 'https://example.com/saudi/alraed.png',
        league: 'Saudi Pro League',
        country: 'Saudi Arabia',
        flag: 'https://example.com/flags/saudiarabia.png',
        stars: 3,
        attack: 69,
        midfield: 67,
        defense: 68,
      },
      {
        name: 'Al-Riyadh',
        logo: 'https://example.com/saudi/alriyadh.png',
        league: 'Saudi Pro League',
        country: 'Saudi Arabia',
        flag: 'https://example.com/flags/saudiarabia.png',
        stars: 2.5,
        attack: 67,
        midfield: 65,
        defense: 65,
      },
      {
        name: 'Al-Taawoun Buraidah',
        logo: 'https://example.com/saudi/altaawounburaidah.png',
        league: 'Saudi Pro League',
        country: 'Saudi Arabia',
        flag: 'https://example.com/flags/saudiarabia.png',
        stars: 3.5,
        attack: 72,
        midfield: 71,
        defense: 69,
      },
      {
        name: 'Al-Fateh',
        logo: 'https://example.com/saudi/alfateh.png',
        league: 'Saudi Pro League',
        country: 'Saudi Arabia',
        flag: 'https://example.com/flags/saudiarabia.png',
        stars: 3,
        attack: 69,
        midfield: 67,
        defense: 68,
      },
      {
        name: 'Al-Fayha',
        logo: 'https://example.com/saudi/alfayha.png',
        league: 'Saudi Pro League',
        country: 'Saudi Arabia',
        flag: 'https://example.com/flags/saudiarabia.png',
        stars: 3,
        attack: 68,
        midfield: 66,
        defense: 67,
      },
      {
        name: 'Al-Khaleej Saihat',
        logo: 'https://example.com/saudi/alkhaleej.png',
        league: 'Saudi Pro League',
        country: 'Saudi Arabia',
        flag: 'https://example.com/flags/saudiarabia.png',
        stars: 2.5,
        attack: 67,
        midfield: 65,
        defense: 65,
      },
      {
        name: 'Al-Hazm',
        logo: 'https://example.com/saudi/alhazm.png',
        league: 'Saudi Pro League',
        country: 'Saudi Arabia',
        flag: 'https://example.com/flags/saudiarabia.png',
        stars: 2.5,
        attack: 66,
        midfield: 64,
        defense: 65,
      },
      {
        name: 'Al-Hilal Riyadh',
        logo: 'https://example.com/saudi/alhilalriyadh.png',
        league: 'Saudi Pro League',
        country: 'Saudi Arabia',
        flag: 'https://example.com/flags/saudiarabia.png',
        stars: 5,
        attack: 80,
        midfield: 78,
        defense: 77,
      },
      {
        name: 'Al-Kholood',
        logo: 'https://example.com/saudi/alkholood.png',
        league: 'Saudi Pro League',
        country: 'Saudi Arabia',
        flag: 'https://example.com/flags/saudiarabia.png',
        stars: 2.5,
        attack: 66,
        midfield: 64,
        defense: 65,
      },
      {
        name: 'Al-Shabab Riyadh',
        logo: 'https://example.com/saudi/alshabab.png',
        league: 'Saudi Pro League',
        country: 'Saudi Arabia',
        flag: 'https://example.com/flags/saudiarabia.png',
        stars: 3.5,
        attack: 72,
        midfield: 70,
        defense: 71,
      },
      {
        name: 'Damk',
        logo: 'https://example.com/saudi/damk.png',
        league: 'Saudi Pro League',
        country: 'Saudi Arabia',
        flag: 'https://example.com/flags/saudiarabia.png',
        stars: 3,
        attack: 69,
        midfield: 67,
        defense: 68,
      },
    ],
  },
];
